academia/academia/doctype/academic_rank/academic_rank.js
academia/academia/doctype/academic_rank/academic_rank.json
academia/academia/doctype/academic_rank/academic_rank.py
academia/academia/doctype/academic_rank/test_academic_rank.py

This commit adds an Academic Rank to be used in Faculty Member

feat(core): Adding Academic Rank Doctype

---

academia/academia/doctype/faculty_member/faculty_member.json
academia/academia/doctype/faculty_member/faculty_member.py

We added some features to the Faculty Member Doctype.

feat(core): Adding Fields, Sections, Tabs to the Faculty Member Doctype

---

academia/academia/doctype/course/course.json

fixing installation ERROR as a solution for #18 issue raised by @MSarari

fix(course): update course.json

---

academia/academia/doctype/course/course.json

This PR is a fixing PR that fix the conflict made in #14 PR in Course Doctype

fix(course): Fixing the conflict made in #14 PR in Course Doctype

---

academia/academia/workspace/academia/academia.json

feat(Workspace): adding academia workspace

---

academia/academia/doctype/academic_status/academic_status.js
academia/academia/doctype/academic_status/academic_status.json
academia/academia/doctype/academic_status/academic_status.py
academia/academia/doctype/academic_status/test_academic_status.py
academia/academia/doctype/place_of_birth/place_of_birth.js
academia/academia/doctype/place_of_birth/place_of_birth.json
academia/academia/doctype/place_of_birth/place_of_birth.py
academia/academia/doctype/place_of_birth/test_place_of_birth.py
academia/academia/doctype/student/student.json
academia/academia/doctype/student_group/student_group.json
academia/academia/doctype/student_state/student_state.js
academia/academia/doctype/student_state/student_state.json
academia/academia/doctype/student_state/student_state.py
academia/academia/doctype/student_state/test_student_state.py
academia/student_enrollment/doctype/semester_enrollment/semester_enrollment.js
academia/student_enrollment/doctype/semester_enrollment/semester_enrollment.json
academia/student_enrollment/doctype/semester_enrollment/semester_enrollment.py
academia/student_enrollment/doctype/semester_enrollment/test_semester_enrollment.py

**We add a new fields in Student doctype:**
**And add some new doctype with fields:**
- Place of Birth 
- Student State
- Academic Status

update(core): Add some fields and doctypes

---

academia/academia/doctype/building/building.js
academia/academia/doctype/building/building.json
academia/academia/doctype/building/building.py
academia/academia/doctype/building/test_building.py
academia/academia/doctype/lab/lab.json
academia/academia/doctype/lab_type/lab_type.js
academia/academia/doctype/lab_type/lab_type.json
academia/academia/doctype/lab_type/lab_type.py
academia/academia/doctype/lab_type/test_lab_type.py
academia/academia/doctype/room/room.json

- add Building Doctype with fields Building Name, Faculty, Address and Description 
- add Lab Type Doctype with fields lab Type, Faculty and Description   
- add fields to Room Doctype Building and faculty
- add fields to lab Doctype: Building and faculty fields

update(core): add a new doctypes with fields

---

academia/academia/doctype/student_batch/student_batch.json

add  Program Specification field to Student Batch Doctype
Some key notes before you open a PR:
1. update Student Batch : add  Program Specification field

update(Core): add  Program Specification field to Student Batch Doctype

---

academia/academia/doctype/program_enrollment/program_enrollment.js
academia/academia/doctype/program_enrollment/program_enrollment.json
academia/academia/doctype/program_enrollment/program_enrollment.py
academia/academia/doctype/program_enrollment/test_program_enrollment.py

**Add Program Enrollment Doctype with fields:**
1. Student
2. Student Name
3. Enrollment Date
4. Program
5. Status
6. Academic Year
7. Academic Term
8. Image
9. Student Batch

add(core): Add Program Enrollment Doctype with fields

---

academia/academia/doctype/course_study_course/course_study_course.json
academia/academia/doctype/course_study_course/course_study_course.py
academia/academia/doctype/course_study_tool/course_study_tool.js
academia/academia/doctype/course_study_tool/course_study_tool.json
academia/academia/doctype/course_study_tool/course_study_tool.py
academia/academia/doctype/course_study_tool/test_course_study_tool.py

I programed this feature tool for generating the courses into the course study by creating two buttons one to get the courses and another to generate the courses.
This commit devloped backend and frontend by python, java-script and frappe form freamwork.

feat(core): Create a tool to generate courses into course study.

---

academia/academia/doctype/course_enrollment_course/course_enrollment_course.json
academia/academia/doctype/course_enrollment_course/course_enrollment_course.py
academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.js
academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.json
academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.py
academia/academia/doctype/course_enrollment_tool/test_course_enrollment_tool.py

I create a Course Enrollment Course as a child table with fields.
and create Course Enrollment Tool doctype with fields.
I create them to generate courses enrollment into course enrollment doctype.

feat(core): Create a tool to generate courses enrollment into course enrollment doctype.

---

academia/academia/doctype/student_group_student/student_group_student.json
academia/academia/doctype/student_group_student/student_group_student.py
academia/academia/doctype/student_group_tool/student_group_tool.js
academia/academia/doctype/student_group_tool/student_group_tool.json
academia/academia/doctype/student_group_tool/student_group_tool.py
academia/academia/doctype/student_group_tool/test_student_group_tool.py

Some key notes before you open a PR:
1.  add student group student with student name ,gander and program fields to doctype
2.   add student group Tool with some fields to doctype

 add(Core): add student group student and Student Grpoup Tool  doctypes 

---

.editorconfig
.github/helper/install.sh
.github/helper/site_config.json
.github/workflows/ci.yml
.github/workflows/linters.yml
.pre-commit-config.yaml
.pre_commit_config.yaml
academia/hooks.py
academia/tests/test_utils.py
commitlint.config.js
pyproject.toml

This pull request introduces significant enhancements to the continuous integration (CI) workflows, code quality checks, and development environment setups for the Academia app. The changes aim to streamline development practices, improve code quality, and ensure a robust testing environment.
Updated the CI configuration to include comprehensive Python unit tests, enhance environment setup .
Add Linter workflow with Integrated advanced code quality checks including commit message linting, Semgrep rules for Python, and pre-commit hooks for automated code formatting.
Introduced .pre-commit-config.yaml  configurations for pre-commit Action  to automate code formatting and linting, reducing manual review time and improving code consistency.
Configured pyproject.toml for consistent code …

feat: Enhance CI Workflow with better environment setup , and add Linter for Code Quality 

---

academia/academia/doctype/program_enrollment/program_enrollment.json
academia/academia/doctype/program_enrollment/program_enrollment.py

feat(core): Add a Check Enabled Field in Program Enrollment Doctype 

---

academia/academia/doctype/faculty_member/faculty_member.py
academia/hooks.py

Fixing bugs and adding a feature 

---

academia/academia/doctype/facility/facility.json
academia/academia/doctype/facility/facility.py
academia/academia/doctype/lesson/lesson.js
academia/academia/doctype/lesson/lesson.json
academia/academia/doctype/lesson/lesson.py
academia/academia/doctype/lesson/test_lesson.py
academia/academia/doctype/schedule_template/schedule_template.js
academia/academia/doctype/schedule_template/schedule_template.json
academia/academia/doctype/schedule_template/schedule_template.py
academia/academia/doctype/schedule_template/test_schedule_template.py
academia/academia/doctype/schedule_template_version/schedule_template_version.js
academia/academia/doctype/schedule_template_version/schedule_template_version.json
academia/academia/doctype/schedule_template_version/schedule_template_version.py
academia/academia/doctype/schedule_template_version/test_schedule_template_version.py
academia/academia/workspace/academia/academia.json

Add a Lesson Doctype with Fields 
Add a Schedule Template Doctype with Fields 
Add a Schedule Template Version Doctype with Fields

Refactoring and Add a New Doctypes with Fields for the preparation group

---

.github/workflows/ci.yml

- Updated GitHub Actions workflow to refine CI triggers.
- Enhanced efficiency by limiting runs to significant code updates only.
- Reduce unnecessary CI activations for non-impactful changes.
- Conserve resources, improving response times for crucial builds.
Reviewers: @alshalabi-su

refactor(ci): streamline CI triggers to reduce redundant runs

---

academia/academia/doctype/course_enrollment_course/course_enrollment_course.json
academia/academia/doctype/course_enrollment_course/course_enrollment_course.py
academia/academia/doctype/course_enrollment_student/course_enrollment_student.json
academia/academia/doctype/course_enrollment_student/course_enrollment_student.py
academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.js
academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.json
academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.py
academia/academia/doctype/course_study_tool/course_study_tool.py
academia/academia/doctype/program_enrollment/program_enrollment.json
academia/student_enrollment/doctype/course_enrollment/course_enrollment.json
academia/student_enrollment/doctype/course_enrollment/course_enrollment.py

Course Enrollment Tool Activating to enroll the students to there courses automatically.

Course Enrollment Tool Activating to enroll the students to there courses automatically.

---

academia/academia/doctype/student_group_tool/student_group_tool.json
academia/academia/doctype/student_group_tool/student_group_tool.py

feat(core): add grouping by to the student group tool to select grouping by Theoretical or Practical

feat(core): add grouping by to the student group tool to select grouping by Theoretical or Practical

---

academia/academia/doctype/student_group/student_group.js
academia/academia/doctype/student_group/student_group.json
academia/academia/doctype/student_group_tool/student_group_tool.js

I make js in Student Group Doctype to send data and i make js in Student Grooup Tool Doctype to receive the data and put it in specific fields...

feat(core): make a js to send and receive data.

---

academia/academia/doctype/program_enrollment/program_enrollment.json
academia/academia/doctype/program_enrollment/program_enrollment.py
academia/academia/doctype/student_group/student_group.json
academia/academia/doctype/student_group/student_group.py
academia/academia/doctype/student_group_student/student_group_student.json
academia/academia/doctype/student_group_tool/student_group_tool.js
academia/academia/doctype/student_group_tool/student_group_tool.json
academia/academia/doctype/student_group_tool/student_group_tool.py

make the student group tool generate groups and do some other changes to other doctypes and fix some conflicts.

feat(core): make the student group tool generate groups and do some other changes and fix some conflicts.

---

academia/student_enrollment/doctype/course_enrollment/course_enrollment.js
academia/student_enrollment/doctype/course_enrollment/course_enrollment.json
academia/student_enrollment/doctype/course_enrollment/course_enrollment.py

"Fix(Core): Update Course Enrollment Doctype with  validation on  fields  "

---

academia/academia/doctype/course_study_tool/course_study_tool.js

add filters to Course Study Tool Doctype

Feat(core): add filters to Course Study Tool Doctype

---

academia/academia/doctype/group_assignment/group_assignment.json
academia/academia/doctype/group_assignment/group_assignment.py
academia/academia/doctype/group_assignment_group/group_assignment_group.json
academia/academia/doctype/group_assignment_group/group_assignment_group.py
academia/academia/doctype/group_assignment_tool/group_assignment_tool.js
academia/academia/doctype/group_assignment_tool/group_assignment_tool.json
academia/academia/doctype/group_assignment_tool/group_assignment_tool.py
academia/academia/doctype/student_group_tool/student_group_tool.json
academia/academia/doctype/student_group_tool/student_group_tool.py

feat(core): upgrade the student group tool to group up to three groups and enable the group assignment tool get courses button and other edits.

feat(core): upgrade the student group tool and enable the group assignment tool and other edits.

---

academia/academia/doctype/group_assignment_tool/group_assignment_tool.py
academia/academia/doctype/lesson/lesson.json
academia/academia/doctype/lesson/lesson.py
academia/academia/doctype/student_group/student_group.js
academia/academia/doctype/student_group/student_group.json
academia/academia/doctype/student_group/student_group.py
academia/academia/doctype/student_group_tool/student_group_tool.py

feat(core): Finish the group assignment tool and upgrade the student group tool to group up to 4 groups and make it get the theoretical students to group them practical groups and refact the lesson doctype to be like the lesson template except the date and other edits.

feat(core): Finish the group assignment tool and upgrade the student group tool and refact the lesson doctype and other edits.

---

academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.js
academia/academia/doctype/group_assignment_tool/group_assignment_tool.js

Add js filter to Course Enrollment Tool and Group Assignment Tool Doctypes

Feat(core): add js filter to Doctypes

---

academia/academia/doctype/academic_term/academic_term.json
academia/academia/doctype/academic_term/academic_term.py
academia/academia/doctype/course_language/course_language.json
academia/academia/doctype/course_language/course_language.py
academia/academia/doctype/program_specification/program_specification.json
academia/academia/doctype/program_specification/program_specification.py

docs(academia): made changes to the doctypes

---

academia/academia/doctype/student_group_tool/student_group_tool.js
academia/academia/doctype/student_group_tool/student_group_tool.json
academia/academia/doctype/student_group_tool/student_group_tool.py

feat(core): Upgrade the student group tool with the perfect way with perfect logic for generating the Theoretical and the Practical groups with an intelligent idea and other updates.

feat(core): Upgrade the student group tool with the perfect way with perfect logic for generating the Theoretical and the Practical groups.

---

academia/fixtures/custom_docperm.json
academia/fixtures/role.json
academia/hooks.py

Create Academic Supervisor role with fixtures in hooks.py with permissions

Feat(core): Create Academic Supervisor role with fixtures in hooks.py with permissions

---

academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.js
academia/academia/doctype/course_study/course_study.js
academia/academia/doctype/course_study/course_study.json
academia/academia/doctype/course_study_tool/course_study_tool.js
academia/academia/doctype/course_study_tool/course_study_tool.json
academia/academia/doctype/course_study_tool/course_study_tool.py
academia/academia/doctype/group_assignment_tool/group_assignment_tool.js
academia/academia/doctype/student_group_tool/student_group_tool.js
academia/academia/doctype/student_group_tool/student_group_tool.json
academia/academia/doctype/student_group_tool/student_group_tool.py

feat(core): Add some validations to the Tools and fix some Errors on them.

feat(core): Add some validations to the Tools and fix some Errors on them.

---

academia/academia/doctype/faculty_member/faculty_member.js
academia/academia/doctype/faculty_member/faculty_member.json
academia/academia/doctype/faculty_member/faculty_member.py
academia/academia/report/faculty_member_details_report/faculty_member_details_report.js
academia/academia/report/faculty_member_details_report/faculty_member_details_report.json
academia/academia/report/faculty_member_details_report/faculty_member_details_report.py
academia/academia/report/faculty_member_report/faculty_member_report.js
academia/academia/report/faculty_member_report/faculty_member_report.json
academia/academia/report/faculty_member_report/faculty_member_report.py
academia/hooks.py

Adding Faculty Member Reports

---

academia/academia/doctype/authority/authority.json

feat: add fixtures

---

README.md
academia/fixtures/wiki_page.json
academia/fixtures/wiki_space.json

There were some default wiki values that were pushed by the Faculty Member project team that caused trouble when installing wiki for other teams. These values have been deleted now.
> Deleted the default values of Wiki Pages and Wiki Space doctypes from the JSON files.
> Added a guide in the README.md file for the teams that haven't created their wiki yet.

Fixed some issues regarding Wiki

---

academia/academia/doctype/faculty_member/faculty_member.json
academia/academia/doctype/faculty_member/faculty_member.py

refactor(academia): add available for work employee to faculty member

---

academia/academia/doctype/lesson_template/lesson_template.json

Add filter fields to Lesson Template DocType.

---

academia/academia/doctype/lab/lab.json
academia/academia/doctype/lab/lab.py

refactor(academia): change lab type from unique to not unique

---

academia/academia/doctype/temporary_import_student/temporary_import_student_list.js

feat(academia): fix import students to program enrollment via excel

---

academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo/outbox_memo.json
academia/transactions/doctype/outbox_memo/outbox_memo.py
academia/transactions/doctype/transaction_recipients_new/transaction_recipients_new.json

Changes on Outbox Memo

---

academia/transactions/doctype/request/request.js
academia/transactions/doctype/request/request.py

feat(transactions):added get recipients functionality

---

academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo/outbox_memo.json
academia/transactions/doctype/outbox_memo/outbox_memo.py
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.js
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.json
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.py
academia/transactions/doctype/outbox_memo_action/test_outbox_memo_action.py

Added Outbox Memo Action for Approve and Reject

---

academia/transactions/doctype/inbox_memo/inbox_memo.js
academia/transactions/doctype/inbox_memo/inbox_memo.json
academia/transactions/doctype/inbox_memo/inbox_memo.py
academia/transactions/doctype/inbox_memo/inbox_memo_list.js
academia/transactions/doctype/inbox_memo_action/inbox_memo_action.js
academia/transactions/doctype/inbox_memo_action/inbox_memo_action.json
academia/transactions/doctype/inbox_memo_action/inbox_memo_action.py

Added Redirect Action with its Functionality

---

academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo/outbox_memo.json
academia/transactions/doctype/outbox_memo/outbox_memo.py
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.js
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.json
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.py

Added a few changes

---

academia/transactions/doctype/inbox_memo/inbox_memo.py
academia/transactions/doctype/inbox_memo_action/inbox_memo_action.py

fix(transactions): fix approve and reject issue on inbox_memo doctype

---

academia/transactions/doctype/inbox_memo/inbox_memo.json
academia/transactions/doctype/inbox_memo/inbox_memo.py
academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo/outbox_memo.json
academia/transactions/doctype/outbox_memo/outbox_memo.py
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.js
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.py
academia/transactions/doctype/request/request.json
academia/transactions/doctype/request/request.py
academia/transactions/doctype/specific_transaction_document/specific_transaction_document.json
academia/transactions/doctype/specific_transaction_document/specific_transaction_document.py
academia/transactions/doctype/transaction_new/transaction_new.json
academia/transactions/doctype/transaction_new/transaction_new.py
academia/transactions/doctype/transaction_related_documents/transaction_related_documents.json
academia/transactions/doctype/transaction_related_documents/transaction_related_documents.py

Added Transaction Reference to the Four Doctypes

---

academia/transactions/doctype/inbox_memo/inbox_memo.py
academia/transactions/doctype/request/request.py

fix(transactions): fix permissions issue

---

academia/transactions/doctype/inbox_memo/inbox_memo.py
academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo/outbox_memo.json
academia/transactions/doctype/outbox_memo/outbox_memo.py
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.js
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.json
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.py
academia/transactions/doctype/specific_transaction_document/specific_transaction_document.py
academia/transactions/doctype/specific_transaction_document_action/specific_transaction_document_action.js
academia/transactions/doctype/specific_transaction_document_action/specific_transaction_document_action.json
academia/transactions/doctype/specific_transaction_document_action/specific_transaction_document_action.py

Along with other fixes
Some key notes before you open a PR:
1. Select which branch should this PR be merged in?
2. PR name follows [convention](http://karma-runner.github.io/4.0/dev/git-commit-msg.html)
3. All tests pass locally, UI and Unit tests
4. All business logic and validations must be on the server-side
5. Update necessary Documentation
6. Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes
Also, if you're new here
- Documentation Guidelines => https://github.com/Sana-a-Uni/Academia
- Contribution Guide => https://github.com/Sana-a-Uni/Academia
- Pull Request Checklist => https://github.com/Sana-a-Uni/Academia
-->
> Explain the …

Fixed Update Share Permission in Outbox and Inbox Memo

---

academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo/outbox_memo.json
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.js
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.py
academia/transactions/doctype/transaction_document_log/transaction_document_log.js
academia/transactions/doctype/transaction_document_log/transaction_document_log.json
academia/transactions/doctype/transaction_document_log/transaction_document_log.py

Added Middle Man Functionality to Redirect in Outbox Memo

---

academia/academia/doctype/course_enrollment/course_enrollment.json
academia/academia/doctype/course_enrollment/course_enrollment.py
academia/academia/doctype/course_enrollment_tool/course_enrollment_tool.py
academia/academia/doctype/course_study/course_study.json
academia/academia/doctype/course_study_tool/course_study_tool.py
academia/academia/doctype/group_assignment/group_assignment.json
academia/academia/doctype/group_assignment/group_assignment.py
academia/academia/doctype/instructor_lessons_template/instructor_lessons_template.json
academia/academia/doctype/instructor_lessons_template/instructor_lessons_template.py
academia/academia/doctype/lesson/lesson.json
academia/academia/doctype/lesson/lesson.py
academia/academia/doctype/lesson_template/lesson_template.json

fix(academia): fixes in several Doctypes

---

academia/transactions/doctype/inbox_memo/inbox_memo.js
academia/transactions/doctype/inbox_memo_action/inbox_memo_action.js
academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo/outbox_memo.json
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.js
academia/transactions/doctype/request/request.js
academia/transactions/doctype/request_action/request_action.js
academia/transactions/doctype/specific_transaction_document/specific_transaction_document.js
academia/transactions/doctype/specific_transaction_document/specific_transaction_document.json
academia/transactions/doctype/specific_transaction_document_action/specific_transaction_document_action.js
academia/transactions/doctype/transaction_new/transaction_new.js
academia/transactions/doctype/transaction_new/transaction_new.json

A Few Features and Fixes

---

academia/transactions/doctype/inbox_memo/inbox_memo.js
academia/transactions/doctype/inbox_memo/inbox_memo.json
academia/transactions/doctype/inbox_memo_action/inbox_memo_action.js
academia/transactions/doctype/inbox_memo_action/inbox_memo_action_list.js
academia/transactions/doctype/outbox_memo/outbox_memo.js
academia/transactions/doctype/outbox_memo_action/outbox_memo_action.js
academia/transactions/doctype/outbox_memo_action/outbox_memo_action_list.js
academia/transactions/doctype/request/request.js
academia/transactions/doctype/request/request.json
academia/transactions/doctype/request_action/request_action.js
academia/transactions/doctype/request_action/request_action_list.js
academia/transactions/doctype/specific_transaction_document/specific_transaction_document.js
academia/transactions/doctype/specific_transaction_document_action/specific_transaction_document_action.js
academia/transactions/doctype/specific_transaction_document_action/specific_transaction_document_action_list.js

fix(transactions): a few fixes
